<!DOCTYPE html>
<html>
    <head>
        <meta name="referrer" content="always" />
        <meta charset='utf-8' />
        <meta name="viewport" content="width=device-width,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no"/>
        <link rel="apple-touch-icon-precomposed" href="//m.baidu.com/static/index/screen_icon.png"/>
        <meta name="format-detection" content="telephone=no"/>
        <title>测试模板，尚未定义</title>
    </head>
    <body>
        <?php echo $contents;?>
        
    </body>
</html>